spring.config.import=optional:classpath:application-local.properties

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sistema_vacunacion?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET}