spring.datasource.url=jdbc:mysql://localhost:3306/sistema_vacunacion?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
jwt.secret=nfweonfnwoemfkmefcmeijqo,lñ,mvcewpofjrhfiohcnjmvoinovinordv
